# Generated by Django 5.0.2 on 2026-08-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_published", "-published_at"],
                name="api_article_is_publ_83ee37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="api_article_slug_867b89_idx"),
        ),
        migrations.AddIndex(
            model_name="modelcheckpoint",
            index=models.Index(
                fields=["is_public", "-created_at"],
                name="api_modelch_is_publ_3fcd83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelcheckpoint",
            index=models.Index(
                fields=["architecture"], name="api_modelch_archite_155262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                fields=["-subscribed_at"], name="api_subscri_subscri_28a3f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                fields=["is_active"], name="api_subscri_is_acti_6bc00c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telemetrylog",
            index=models.Index(
                fields=["-timestamp"], name="api_telemet_timesta_44166b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telemetrylog",
            index=models.Index(
                fields=["event_type"], name="api_telemet_event_t_ae8f41_idx"
            ),
        ),
    ]
